name: 'Configure AWS credentials'
description: 'Set up AWS credentials using GitHub Secrets'
inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        echo "[default]" > ~/.aws/credentials && \
        echo "aws_access_key_id=${{ inputs.aws-access-key-id }}" >> ~/.aws/credentials && \
        echo "aws_secret_access_key=${{ inputs.aws-secret-access-key }}" >> ~/.aws/credentials && \
        echo "[default]" > ~/.aws/config && \
        echo "region=${{ inputs.aws-region }}" >> ~/.aws/config