apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 65
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api