name: 'Set up Terraform'
description: 'Set up Terraform CLI'
inputs:
  tf_version:
    description: 'Terraform version'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        sudo apt-get update && \
        sudo apt-get install -y unzip && \
        curl -o terraform.zip https://releases.hashicorp.com/terraform/${{ inputs.tf_version }}/terraform_${{ inputs.tf_version }}_linux_amd64.zip && \
        unzip terraform.zip && \
        sudo mv terraform /usr/local/bin/ && \
        terraform -version