name: Terraform Deployment Aws

on:
  pull_request:
    branches: [ "main" ]
    types: [ "closed" ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: ./path/to/local/checkout-action

    - name: Set up Terraform
      uses: ./path/to/local/setup-terraform-action
      with:
        tf_version: 1.0.0

    - name: Configure AWS credentials
      uses: ./path/to/local/configure-aws-credentials-action
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform init
      run: terraform init -upgrade

    - name: Terraform plan
      run: terraform plan

    - name: Terraform apply
      run: terraform apply -auto-approve
